Add method that generates keys to the `DataProcessor`
sdv-dev/SDV pull request #1017
Opened 2022-09-20 14:04 UTC by pvk-developer

Resolves #994

2022-09-20 21:44 UTC, amontanez24 requested changes
This looks mostly good! Just a few small comments and questions

2022-09-20 21:44 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +            self._primary_keys = list(cast_to_iterable(self.metadata._primary_key))
why do we need this? Can't we just reference the primary key through the metadata wherever we need it

2022-09-20 21:44 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +        regex_format = column_metadata.get('regex_format')
why not check that the sdtype is `text`?

2022-09-20 21:44 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +            column_metadata['enforce_uniqueness'] = True
Idk if we should alter the original metadata. Maybe we should copy the dict if we are going to add to it

2022-09-20 21:44 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
>              if column_metadata.get('pii'):
this is the same check as on line 259. Why not just move the line underneath to there?

2022-09-21 00:33 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +        else:
what if the primary key is an int? We should be able to generate a range like we used to

2022-09-21 19:27 UTC, amontanez24 approved these changes
This looks good, but can we update the docstrings for the tests to match our new standard?

2022-09-21 19:27 UTC, amontanez24 commented on tests/integration/data_processing/test_data_processor.py
> +    Side effects:
I thought we were going to alabel this section `Assert` to match the sections in the test

2022-09-21 19:40 UTC, fealho reviewed
Looks good! I just have one question regarding what happens when primary_keys is a tuple.

2022-09-21 19:40 UTC, fealho commented on sdv/data_processing/data_processor.py
> +            column_names=[self._primary_key]
I believe `self._primary_key` can be a tuple, since it can be set in line 248. In such cases we would want to pass each of them separately no?

2022-09-21 20:32 UTC, fealho approved these changes

2022-09-30 18:42 UTC, amontanez24 reviewed
Changes look good to me! Once the test coverage for the unit tests is 100% :shipit:

2022-09-30 18:42 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +            if reset_primary_key:
do we need to add a unit test for this case?

2022-10-04 11:32 UTC, merged