Add `update_transformers` to `BaseSynthesizer`
sdv-dev/SDV pull request #1058
Opened 2022-10-05 16:04 UTC by fealho

Resolve #1021.

2022-10-05 20:00 UTC, amontanez24 requested changes

2022-10-05 20:00 UTC, amontanez24 commented on sdv/single_table/base.py
> +    def _warn(self, column_name_to_transformer):
minor: maybe make this more descriptive. `_raise_transformer_update_warnings` or `_warn_for_transformer_updates`

2022-10-05 20:00 UTC, amontanez24 commented on sdv/single_table/copulas.py
> +                warnings.warn(
I think there should be one more warning like this on the other models for when categorical  or boolean transformers are set

2022-10-06 15:56 UTC, fealho commented on sdv/single_table/base.py
> +            if sdtype != transformer.get_input_sdtype():
Good catch

2022-10-07 21:21 UTC, amontanez24 approved these changes
LGTM!

2022-10-12 17:03 UTC, merged