Add preprocess to synthesizers
sdv-dev/SDV pull request #1067
Opened 2022-10-17 20:30 UTC by pvk-developer

Resolves #1018

2022-10-18 19:53 UTC, amontanez24 requested changes

2022-10-19 01:26 UTC, fealho reviewed
Looks good! I'm just not sure whether you implemented the last comment in the issue (`If the HyperTransformer has not already been created, this method can call the assign_transformers method added in`)?

2022-10-19 01:26 UTC, fealho commented on tests/unit/data_processing/test_data_processor.py
> +        instance._transformers_by_sdtype == {
add assert

2022-10-19 01:26 UTC, fealho commented on tests/unit/single_table/test_base.py
> +        Before the preprocessing is occurs we check that the synthesizer has
typo: delete is

2022-10-19 08:23 UTC, pvk-developer commented on sdv/single_table/base.py
> +                self._data_processor._update_transformers_by_sdtypes(sdtype, transformer)
Yes we can move it to the `init`

2022-10-19 14:39 UTC, fealho commented on tests/unit/single_table/test_base.py
> +        """
Perhaps you could be slightly more descriptive in the docstring.

2022-10-19 17:18 UTC, amontanez24 approved these changes
:shipit:

2022-10-19 17:21 UTC, fealho approved these changes

2022-10-19 21:58 UTC, merged