Create a utility to load multiple tables at once
sdv-dev/SDV pull request #1084
Opened 2022-10-24 21:41 UTC by amontanez24

resolves #969

2022-10-25 20:02 UTC, pvk-developer requested changes

2022-10-25 20:02 UTC, pvk-developer commented on sdv/utils.py
> +def load_data_from_csv(filepath, pandas_kwargs):
`pandas_kwargs=None` otherwise we have to always pass it in

2022-10-26 10:26 UTC, pvk-developer approved these changes

2022-10-26 16:42 UTC, fealho approved these changes

2022-11-04 21:43 UTC, fealho approved these changes

2022-11-04 21:43 UTC, fealho commented on tests/unit/datasets/test_local.py
> +    """Test that the funcction loads only the csv files in a folder.
funcction

2022-11-07 13:10 UTC, pvk-developer approved these changes

2022-11-07 18:00 UTC, merged