Add `get_learned_distributions` for `GaussianCopulaSynthesizer` and `CopulaGANSynthesizer`
sdv-dev/SDV pull request #1097
Opened 2022-11-13 20:01 UTC by pvk-developer

Resolves #1075

2022-12-17 00:17 UTC, amontanez24 requested changes
The issue also asks for a multi-table version of this method which is essentially just a wrapper around the single-table version. Let's add that and then this should be good!

2022-12-17 00:17 UTC, amontanez24 commented on tests/unit/single_table/test_copulas.py
> +                'distribution': 'beta',
can we test multiple distribution types?

2022-12-20 20:51 UTC, amontanez24 reviewed
One comment, then looks good to me!

2022-12-20 20:51 UTC, amontanez24 commented on sdv/single_table/copulas.py
> +            for valid_column in metadata_columns:
As opposed to looping through these each time, can we do one pass and just get all the valid columns and the just loop through those to set the distributions?

2022-12-21 04:26 UTC, fealho approved these changes
Besides Andrews comment, looks good👍

2022-12-21 18:02 UTC, amontanez24 approved these changes
:shipit:

2022-12-21 18:04 UTC, merged