Allow me to create a `Custom Constraint Class` and use it in the same file (`filepath=None`)
sdv-dev/SDV pull request #1223
Opened 2023-02-02 03:42 UTC by amontanez24

resolves #1205

2023-02-02 11:07 UTC, pvk-developer requested changes
Just a few comments, but then it should be good!
Also I realized there are no integration tests for `multi_table` for both `load` and `add` do you mind adding those ? Or we can address it later.

2023-02-02 20:36 UTC, amontanez24 commented on sdv/data_processing/data_processor.py
> +        self._custom_constraint_classes[class_name] = class_object
good catch

2023-02-02 22:16 UTC, pvk-developer approved these changes
🚢 LG to me.

2023-02-03 20:59 UTC, fealho approved these changes
Pretty good 👍

2023-02-03 20:59 UTC, fealho commented on tests/integration/single_table/custom_constraints.py
> +    data[column_names] = data[column_names] ** 2
Good catch!

2023-02-03 21:17 UTC, merged