Validate `numerical_distrubutions` parameter
sdv-dev/SDV pull request #1234
Opened 2023-02-06 03:01 UTC by fealho

Resolve #1211.

2023-02-06 21:58 UTC, fealho commented
The issue only mentions `GaussianCopulaSynthesizer`, but I believe `CopulaGANSynthesizer` should be updated as well.

2023-02-07 00:42 UTC, amontanez24 approved these changes
LGTM!

2023-02-07 11:20 UTC, pvk-developer requested changes
Just some refactoring to reuse the same piece of code and not duplicate it then it should be good to go.

2023-02-07 11:20 UTC, pvk-developer commented on sdv/single_table/copulas.py
> +
Lets convert this into a `staticmethod` that takes `columns` and `numerical_distributions`, then we can re-use it in the `copulagan` by using `GaussianCopulaSynthesizer._validate_numerical_distributions(...)` and not having the code duplicated.

2023-02-07 11:20 UTC, pvk-developer commented on sdv/single_table/copulagan.py
> +                )
This can be removed if the other comment gets addressed.

2023-02-07 11:20 UTC, pvk-developer commented on sdv/single_table/copulagan.py
> +        self._validate_numerical_distributions(numerical_distributions)
This can be changed for `GaussianCopulaSynthesizer._validate_numerical_distributions(numerical_distributions, self.metadata._columns)`

2023-02-07 14:54 UTC, pvk-developer approved these changes

2023-02-07 16:01 UTC, merged