Allow IDGenerator be used for Primary and Alternate Keys
sdv-dev/SDV pull request #1892
Opened 2024-04-04 16:27 UTC by lajohn4747

resolves #1862 
CU_86aztbydu

Allow IDGenerator transformer to be used for primary and alternate keys

2024-04-06 11:24 UTC, pvk-developer approved these changes

2024-04-06 16:12 UTC, amontanez24 requested changes
Let's add an integration test that covers the example in the issue

2024-04-08 20:06 UTC, amontanez24 commented on tests/integration/data_processing/test_data_processor.py
> +        """ Test that updating to transformer to id generator is valid"""
sorry, for this I meant can we test from the synthesizer level like in the issue. Set up a synthesizer and attempt to assign it the transformer and see if everything works end to end

2024-04-09 14:57 UTC, amontanez24 approved these changes

2024-04-09 15:48 UTC, merged