Warn the user if they are trying to save an unfit synthesizer
sdv-dev/SDV pull request #2147
Opened 2024-07-25 17:06 UTC by fealho

CU-86b06q2kq, Resolve #1961.

2024-07-25 17:06 UTC, sdv-team commented
Task linked: [CU-86b06q2kq SDV - Warn the user if they are trying to save an unfit synthesizer #1961](https://app.clickup.com/t/86b06q2kq)

2024-07-26 15:49 UTC, gsheni requested changes

2024-07-26 15:49 UTC, gsheni commented on tests/unit/multi_table/test_base.py
> +            filepath = tmp_path / 'output.pkl'
Use `os.path.join`

2024-07-26 15:49 UTC, gsheni commented on tests/unit/single_table/test_base.py
> +            filepath = tmp_path / 'output.pkl'
Use `os.path.join`

2024-07-26 17:46 UTC, gsheni approved these changes

2024-07-29 08:57 UTC, R-Palazzo approved these changes

2024-07-29 12:27 UTC, merged