Change the code related to `pydrive` and use `google-api` instead
sdv-dev/SDV pull request #2254
Opened 2024-10-04 11:33 UTC by pvk-developer

Resolves #2238 
This `pr` changes the usage of `pydrive` to official `google` api calls without the need of third party libraries like `PyDrive2` or the currently deprecated `PyDrive`.

CU-86b29t2nz

2024-10-04 11:33 UTC, sdv-team commented
Task linked: [CU-86b29t2nz SDV - Use PyDrive2 instead of PyDrive #2238](https://app.clickup.com/t/86b29t2nz)

2024-10-04 15:19 UTC, amontanez24 requested changes
I think we can simplify the authentication section. We never authenticate by loading from a json file on the user's machine so I don't think we need that option. We can either just refresh the credentials like we do or use InstalledAppFlow.from_client_config and just load from the string

2024-10-04 16:28 UTC, pvk-developer commented on tests/_external/gdrive_utils.py
> +            flow = InstalledAppFlow.from_client_secrets_file('client_secrets.json', SCOPES)
Oh sorry this was from my local. I will remove it

2024-10-07 13:06 UTC, pvk-developer commented
> I think we can simplify the authentication section. We never authenticate by loading from a json file on the user's machine so I don't think we need that option. We can either just refresh the credentials like we do or use InstalledAppFlow.from_client_config and just load from the string

Yes I agree, I addressed this here:
https://github.com/sdv-dev/SDV/pull/2254/commits/8de9442f5ee4641776638403de566dddf9ac5c42

2024-10-07 16:53 UTC, amontanez24 approved these changes
LGTM!

2024-10-07 18:43 UTC, lajohn4747 approved these changes

2024-10-09 16:55 UTC, amontanez24 approved these changes
LGTM! 🚢

2024-10-09 22:07 UTC, merged