sdv-379-p2: Catch MissingConstraintColumnError and skip conditioning on that constraint
sdv-dev/SDV pull request #426
Opened 2021-05-11 21:09 UTC by amontanez24

2021-05-14 17:44 UTC, csala requested changes
This looks very good so far @amontanez24 !
I added a couple of style comments and a warning about a test that might not be completely right.
Also, I would add at least 1 small integration test that certifies that the functionality is properly covered, mocking the underlying `GaussianMultivariate` to make the test faster and also be able to check that the conditions that reach the model are the expected ones. For this test, I would send 2 condition columns, one which can be passed and another one that cannot (for example, create a UniqueCombinations on `city` and `state`, and condition on `age` and `state`, which should make only `age` reach the copula model).

2021-05-14 17:44 UTC, csala commented on sdv/metadata/table.py
> +        return data
Could we add a line break above this line?

2021-05-14 17:44 UTC, csala commented on sdv/metadata/table.py
> +                elif on_missing_column == 'drop':
Maybe we should add and `else` branch that raises a `ValueError`

2021-05-14 17:44 UTC, csala commented on sdv/tabular/base.py
> +            condition = dict(zip(condition_columns, group))
Can we add a line break above?

2021-05-14 17:44 UTC, csala commented on tests/unit/constraints/test_base.py
> +        instance.constraint_columns = ('a')
I think that this should be `('a', )`, otherwise it is equivalent to `'a'`, without the tuple.

2021-05-14 17:44 UTC, csala commented on tests/unit/metadata/test_table.py
> +    def test__make_ids_unique_field_not_unique(self):
Good catch!

2021-05-14 17:44 UTC, csala commented on tests/unit/metadata/test_table.py
> +        """Test that the `transform` method calls `_transform_constraints` with right parameters"""
Could we add some more details about what is being tested, like in the test below?

2021-05-18 15:30 UTC, csala requested changes
I think we are almost there :-)
I added 2 comments about an invalid variable name and another assert that I would like to add to the integration test.

2021-05-18 17:13 UTC, amontanez24 commented on tests/unit/metadata/test_table.py
> +        expectedData = pd.DataFrame({
good catch! Old habits die hard

2021-05-19 17:11 UTC, csala approved these changes
Looks good now! It can be merged.

2021-05-19 17:33 UTC, merged