Change rtol comparison from < to <=
sdv-dev/SDV pull request #527
Opened 2021-07-28 16:41 UTC by shlomihod

Fix for issue #525: trying to apply a condition on sampling with the value 0. for a float column leads to an exception.

2021-07-28 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sdv-dev/SDV?pullRequest=527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sdv-dev/SDV?pullRequest=527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sdv-dev/SDV?pullRequest=527) it.</sub>

2021-08-03 10:30 UTC, csala requested changes
I think looks good @shlomihod 
What do you think about also adding an integration test to validate that it works as expected (and continues to do so in the future)?

I would add it in `tests/integration/tabular/test_base.py`, something similar to the 
`test_conditional_sampling_graceful_reject_sampling_True_dict` test: https://github.com/sdv-dev/SDV/blob/08af5aa6c8ae4c6e1246c425b735a581cc52fd9b/tests/integration/tabular/test_base.py#L22
But setting dtype float, conditioning on `{'column1': 0.0}`, and then, instead of expecting an Exception, capturing the output and validating that column1 is actually 0.0 in the returned DataFrame.

2022-04-10 16:31 UTC, tssbas commented
Dear @csala I am experiencing the same problem as described in #527 . After debugging I have come to the same conclusion that the "less than" should actually be "less or equal to". I wanted to submit a pull request but now I see that this fix already exists, but for some reason still hasn't been merged. Is there any chance this PR gets merged and included in the next release of SDV?

Thanks!

2022-04-12 14:57 UTC, katxiao commented
Hi @shlomihod, could you add the unit test that csala requested?

2022-04-28 16:45 UTC, closed without merging