Create sdv presets
sdv-dev/SDV pull request #720
Opened 2022-03-03 17:32 UTC by katxiao

Resolves #715 
Resolves #716

2022-03-04 22:58 UTC, amontanez24 requested changes
This looks good. One question I have is why not make it a child class of the tabular model that sets these parameters based on the preset selected during the `__init__`. If this were the case, it would also be able to use functions like `sample_conditions` or anything else the tabular model offers

2022-03-04 22:58 UTC, amontanez24 commented on sdv/lite/tabular.py
> +    def list_available_presets(cls):
Can we add unit tests for this and make sure it prints properly in the scenario where there are multiple presets?

2022-03-16 14:09 UTC, katxiao commented
> This looks good. One question I have is why not make it a child class of the tabular model that sets these parameters based on the preset selected during the `__init__`? If this were the case, it would also be able to use functions like `sample_conditions` or anything else the tabular model offers

Yeah that's a good question. We also want to add logic that wraps around the tabular model, such as some data pre- and post- processing. I thought it would be more straightforward to wrap around the Tabular model itself.

2022-03-16 20:57 UTC, amontanez24 approved these changes
:shipit:

2022-03-17 16:00 UTC, merged