Split `GreaterThan` into `Inequality` and `ScalarInequality`
sdv-dev/SDV pull request #823
Opened 2022-05-26 00:17 UTC by fealho

Resolve #814.

2022-06-03 20:46 UTC, amontanez24 requested changes
I checked the coverage report and for `sdv/contraints/tabular.py`, the following lines need to be tested:
https://github.com/sdv-dev/SDV/blob/issue-814-split-greaterthan/sdv/constraints/tabular.py#L304

https://github.com/sdv-dev/SDV/blob/issue-814-split-greaterthan/sdv/constraints/tabular.py#L420

https://github.com/sdv-dev/SDV/blob/issue-814-split-greaterthan/sdv/constraints/tabular.py#L441

All of them seem related to raising errors. Can we add these unit tests in?

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - Raise ``ValueError`` because column names must be strings
This should say: `because strict_boundaries must be a boolean`

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - instance._dtype = None
This is basically just copying the code and doesn't really add anything. Instead can we describe why certain parameters are being set as certain values?

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - _is_datetime should receive the output of _get_is_datetime
Does `is_datetime` have the preceding `_` or not, or are there two different variables?

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - _dtype should be a list of float dtypes.
Is it a list or just a single dtype?

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - _dtype should be a list of datetime dtypes.
same

2022-06-03 20:46 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        - instance._is_datetime = None
Same thing here. Let's describe why the parameters are being set to these values rather than listing them

2022-06-06 19:49 UTC, amontanez24 approved these changes
Assuming the test coverage is now 100% this looks good to go!

2022-06-08 09:15 UTC, pvk-developer approved these changes

2022-06-09 11:57 UTC, merged