Split Between into Range and ScalarRange
sdv-dev/SDV pull request #832
Opened 2022-06-03 18:13 UTC by pvk-developer

Resolves #815

2022-06-08 01:16 UTC, amontanez24 requested changes
A few nitpicks and a suggestion to move the sigmoid/logit functions into a utils module

2022-06-08 01:16 UTC, amontanez24 commented on sdv/constraints/tabular.py
> +      of two other scalar values.
nitpick: you can just says scalars since you already said values before

2022-06-08 01:16 UTC, amontanez24 commented on sdv/constraints/tabular.py
> +        data = data.clip(self.low_value, self.high_value)
Perhaps we should make util functions called `sigmoid` and `logit` that do these operations. That way the code doesn't get reused in two places and we provide some context to the operations. We can also handle the precision problem in those functions

2022-06-08 01:16 UTC, amontanez24 commented on sdv/constraints/tabular.py
> +            table_data[self.column_name] = pd.to_datetime(data.round('1000ms'))
if the precision problem is fixed, lets get rid of this rounding

2022-06-08 11:25 UTC, pvk-developer commented on tests/unit/constraints/test_tabular.py
> +        """"Test the ``reverse_transform`` method for ``Range``.
Nice catch 👍🏻

2022-06-08 17:23 UTC, amontanez24 reviewed
Almost ready! One last comment about unit tests

2022-06-08 17:23 UTC, amontanez24 commented on tests/unit/constraints/test_tabular.py
> +        expected_transform = logit(
For the unit tests, let's just make sure `logit` and `sigmoid` are called with the correct parameters and we use whatever they return correctly. Then we can add unit tests for those functions specifically

2022-06-09 13:39 UTC, fealho approved these changes
Looks good! Left a couple of comments, after that should be good to go.

2022-06-10 16:55 UTC, amontanez24 approved these changes
Thanks for addressing the comments :shipit:

2022-06-10 17:57 UTC, fealho reviewed
👍

2022-06-10 18:14 UTC, merged