Update `RDT` to v1.0.0
sdv-dev/SDV pull request #923
Opened 2022-07-25 14:28 UTC by pvk-developer

Resolves #897

2022-07-27 21:00 UTC, amontanez24 requested changes
Mostly minor comments and questions

2022-08-01 18:11 UTC, amontanez24 approved these changes
One more minor comment, but after that looks ready to go to me!

2022-08-01 18:11 UTC, amontanez24 commented on sdv/metadata/table.py
>                  transformer_template = self._dtype_transformers[np.dtype(dtype).kind]
you can probably add this as the default to the get on line 406 so you only have to do this check once. ie
```python
transformer_template = field_metadata.get('transformer', self._dtype_transformers[np.dtype(dtype).kind])
```

2022-08-02 04:44 UTC, fealho approved these changes
Looks good! Just double check why the tutorials are failing.

2022-08-02 14:51 UTC, merged