Add visualize method to MultiTableMetadata class
sdv-dev/SDV pull request #931
Opened 2022-07-29 16:58 UTC by amontanez24

2022-08-01 03:46 UTC, fealho approved these changes
Looks good 👍

2022-08-01 03:46 UTC, fealho commented on tests/unit/metadata/test_multi_table.py
> +        """Set the tables and relationships for metadata"""
. at the end

2022-08-01 21:40 UTC, pvk-developer requested changes

2022-08-01 21:40 UTC, pvk-developer commented on sdv/metadata/multi_table.py
> +    def visualize(self, show_table_details, show_relationship_labels, output_filepath=None):
I think that `show_table_dateils` and `show_relationship_labels` should default to some value as we want to be able to run `digraph = metadata.visualize()` .

2022-08-01 21:40 UTC, pvk-developer commented on sdv/metadata/multi_table.py
> +    def visualize(self, show_table_details, show_relationship_labels, output_filepath=None):
Should `show_table_details` and `show_relationship_labels` be optional, and be able to run `digraph = metadata.visualize()` ?

2022-08-01 22:05 UTC, pvk-developer approved these changes

2022-08-02 04:45 UTC, fealho approved these changes

2022-08-02 17:56 UTC, pvk-developer approved these changes

2022-08-02 18:00 UTC, merged